MVC/Controllers/ServerDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC.Models;
using RestSharp;
using MVC.Helper;

namespace MVC.Controllers
{
    public class ServerDataController : Controller
    {
        //www.c-sharpcorner.com/UploadFile/g_arora/how-to-consume-Asp-Net-web-api-from-Asp-Net-mvc4-using-rests/

        static readonly IServerDataRestClient RestClient = new ServerDataRestClient();
        public ActionResult Index()
        {
            return View(RestClient.GetAll());
        }
    }
}

MVC/Views/ServerData/Index.cshtml
@model IEnumerable<MVC.Models.ServerDataModel>

@{
    ViewBag.Title = "Manipulate Server Data";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Consume Asp.net WebAPI :: Server Data</h2>

<article>
    <p>
        Here you can manipulat server data.
    </p>

    <p>
        @Html.ActionLink("Create New", "Create", null, new { @class = "actionlinkbutton" })
    </p>

    <div>
        <table>

            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.InitialDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EndDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OrderNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsDirty)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IP)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Type)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RecordIdentifier)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.InitialDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderNumber)
                    </td>
                    <td>
                        @string.Format(item.IsDirty ? "Yes" : "No")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IP)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RecordIdentifier)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }

        </table>
    </div>
</article>

<aside>
    <h3>Navigation</h3>
    <p>
        From here you can navigate other parts of app.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("Manipulate Data", "Index", "ServerData")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>